import Head from 'next/head'
import styles from '../styles/Home.module.css'
import ProductList from '../components/catalog/ProductList';

export const Home = ({ data }) => {
  const { products } = data;
  return (
    <div className={styles.container}>
      <Head>
        <title>Catalog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main className={styles.main}>
        
        <ProductList products={products} />
      </main>
    </div>
  )
}

export async function getServerSideProps() {
  
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}pages/obektivy`)
  const data = await res.json()

  return {
    props: {
      data
    }
  }
}

export default Home;